desc "starting application task"
task :start => [:setup, :build]

desc "setup task before starting application"
task :setup do
  #sh 'bundle install --path vendor/bundle'
  sh 'pod install'
end

desc "execution task for run application"
task :build do
  sh '(JS_DIR=`pwd`/ReactComponent; cd Pods/React; npm run start -- --root $JS_DIR)'
end
